config_version: 1

database_host: "host"
database_port: "3242"
database_dbname: "dbname"
database_username: "username"
database_password: "password"

inode_info_directory: "/etc/marlinstash/inode"

services:
  - service: "bootstrap"
    logrootdir: "/var/log/supervisor"
    fileregex: "bootstrap[0-9]+.log"
  - service: "relay"
    logrootdir: "/var/log/supervisor"
    fileregex: "relay*.log"