config_version: 1

database_host: "127.0.0.1"
database_port: "5432"
database_dbname: "postgres"
database_username: "marlin"
database_password: "linmar"

host: "defaulttailer"

cycle_wait_periods: 2
inactive_time_secs: 10

services:
  - service: "testing"
    logrootdir: "/tmp/tailtest"
    fileregex: "example.log"