config_version: 1

database_host: "127.0.0.1"
database_port: "5432"
database_dbname: "postgres"
database_username: "marlin"
database_password: "linmar"

host: "defaulttailer"

services:
  - service: "probe"
    logrootdir: "/tmp/tailtest"
    fileregex: "nohup\\.out(\\.[0-9]+)?"