config_version: 1

database_host: "host"
database_port: "3242"
database_dbname: "dbname"
database_username: "username"
database_password: "password"

services:
  - name: "hello"
    user: "general"
  - name: "hello"
    user: "nongen"